name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B verify sonar:sonar --file pom.xml -Dsonar.organization=backbase-technology-prototyping -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a8f8241affc8f3da486aa43b81300ac1f0275fa4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}